name: Build & Unit Tests
on: pull_request

jobs:
  code-format:
    name: Check Clang Format
    runs-on: ubuntu-20.04
    steps:
      - name: Prepare OS
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang-format-8 git colordiff
          sudo ln -s /usr/bin/clang-format-diff-8 /usr/bin/clang-format-diff
      - uses: actions/checkout@v1
      - name: Clang format
        run: |
          git remote set-branches --add origin $GITHUB_BASE_REF
          git fetch
          ./run-clang-format-diff.sh origin/$GITHUB_BASE_REF

  build1804gcc:
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-18.04
      compiler: gcc
      unit: false

  build1804clang:
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-18.04
      compiler: clang
      unit: false

  build2004gcc:
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-20.04
      compiler: gcc
      unit: true

  build2004clang:
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-20.04
      compiler: clang
      unit: false
